#!/usr/bin/env python3
"""
Constants for grin-to-s3 application.

Centralized constants to eliminate duplication across the codebase.
"""

# GRIN API rate limiting
GRIN_RATE_LIMIT_QPS = 5.0
GRIN_RATE_LIMIT_DELAY = 0.2  # 1/5 = 0.2 seconds for 5 QPS

# GRIN queue and processing limits
GRIN_MAX_QUEUE_SIZE = 50000
GRIN_DEFAULT_BATCH_SIZE = 200

# Conversion request defaults
DEFAULT_CONVERSION_REQUEST_LIMIT = 5000

# Sync configuration defaults
DEFAULT_SYNC_DISK_SPACE_THRESHOLD = 0.9

# Task concurrency defaults
DEFAULT_SYNC_TASK_CHECK_CONCURRENCY = 2
DEFAULT_SYNC_TASK_DOWNLOAD_CONCURRENCY = 4
DEFAULT_SYNC_TASK_DECRYPT_CONCURRENCY = 20
DEFAULT_SYNC_TASK_UPLOAD_CONCURRENCY = 20
DEFAULT_SYNC_TASK_UNPACK_CONCURRENCY = 20
DEFAULT_SYNC_TASK_EXTRACT_MARC_CONCURRENCY = 20
DEFAULT_SYNC_TASK_EXTRACT_OCR_CONCURRENCY = 20
DEFAULT_SYNC_TASK_EXPORT_CSV_CONCURRENCY = 20
DEFAULT_SYNC_TASK_CLEANUP_CONCURRENCY = 20

# Worker concurrency defaults
DEFAULT_WORKER_CONCURRENCY = 100

# S3 connection pool configuration
# Set to 1.5x the worker concurrency to handle burst traffic
DEFAULT_S3_MAX_POOL_CONNECTIONS = 150
